name: Scheduled Smart Contract Deployment

on:
  schedule:
    - cron: "*/10 * 25 10 *"

env:
  PRIVATE_KEYS: ${{ secrets.PRIVATE_KEYS }}
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Deploy smart contract
        run: hardhat ignition deploy ignition/modules/Bambo139.ts  --network arbitrumSepolia --verify
